apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: syfosmoppgave
  namespace: teamsykmelding
  labels:
    team: teamsykmelding
spec:
  image: {{ image }}
  replicas:
    min: 1
    max: 2
    cpuThresholdPercentage: 90
  port: 8080
  liveness:
    path: /is_alive
    initialDelay: 10
    timeout: 5
    periodSeconds: 5
    failureThreshold: 30
  readiness:
    path: /is_ready
    initialDelay: 30
    periodSeconds: 5
    timeout: 1
  prometheus:
    enabled: true
    path: /prometheus
  observability:
    autoInstrumentation:
      enabled: true
      runtime: java
    logging:
      destinations:
        - id: loki
        - id: elastic
  resources:
    limits:
      memory: 1Gi
    requests:
      cpu: 40m
      memory: 512Mi
  azure:
    application:
      enabled: true
      tenant: trygdeetaten.no
  accessPolicy:
    inbound:
      rules:
        - application: macgyver
        - application: syfosminfotrygd
    outbound:
      external:
        - host: oppgave-q1.dev-fss-pub.nais.io
  kafka:
    pool: nav-dev
  secureLogs:
    enabled: true
  env:
    - name: OPPGAVEBEHANDLING_URL
      value: https://oppgave-q1.dev-fss-pub.nais.io/api/v1/oppgaver
    - name: OPPGAVE_SCOPE
      value: api://dev-fss.oppgavehandtering.oppgave-q1/.default
